# Generated by Django 2.2.7 on 2019-11-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191111_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='github',
            field=models.URLField(default='', max_length=100),
        ),
    ]
